Don't dump wiki content into distribution package.
As requested by Martin[1].

Before releasing a new formal version, run:
$ make Generate-ChangeLog

It generates the ChangeLog out of svn and autoreconf again for package inclusion.

[1] http://www.opensc-project.org/pipermail/opensc-devel/2010-September/015014.html



git-svn-id: https://www.opensc-project.org/svnp/opensc/trunk@4776 c6295689-39f2-0310-b995-f0e70906c6a9

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -24,3 +24,19 @@ dist_doc_DATA = NEWS
 # Allow detection of packaged tarball
 dist-hook:
 	echo > "$(distdir)/packaged"
+
+Generate-ChangeLog:
+	rm -f ChangeLog.tmp "$(srcdir)/ChangeLog"
+	test -n "$(SVN)" -a -n "$(XSLTPROC)"
+	if test -d "$(top_srcdir)/.svn"; then \
+		$(SVN) --verbose --xml log "$(top_srcdir)" | \
+			$(XSLTPROC) --nonet --stringparam linelen 75 \
+			--stringparam groupbyday no \
+			--stringparam include-rev no \
+			"$(top_srcdir)/doc/svn2cl.xsl" - > ChangeLog.tmp; \
+	else \
+		echo "Warning: Unable to generate ChangeLog from none svn checkout" >&2; \
+		echo > ChangeLog.tmp; \
+	fi
+	mv ChangeLog.tmp "$(srcdir)/ChangeLog"
+	( cd "$(srcdir)" && autoreconf -ivf )
